#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the superReducedString function below.
def superReducedString(s):
    for i in range(0,len(s)-1):
        if s[i]==s[i+1]:
            s1=s[0:i]
            if (i+2)<=len(s):
                s2=s[i+2:]
            else:
                s2=""
            s=s1+s2
            s=superReducedString(s)
            break
    if(s==""):
        s="Empty String"
    return s

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = superReducedString(s)

    fptr.write(result + '\n')

    fptr.close()
